function updateLoanPreview(){const terms=calcTerms($('#principal').value,$('#interestRate').value,$('#feeType').value,$('#feeValue').value);$('#previewInterest').textContent=money(terms.interest);$('#previewFee').textContent=money(terms.fee);$('#previewTotal').textContent=money(terms.total);$('#previewTerm').textContent=`Due after ${$('#durationValue').value||0} ${$('#durationUnit').value}. Interest is applied once for the full loan period.`}
function updateDueFromDuration(){if(!$('#dateGiven').value||!$('#timeGiven').value)return;const due=addDuration($('#dateGiven').value,$('#timeGiven').value,$('#durationValue').value,$('#durationUnit').value);$('#dueDate').value=due.date;$('#dueTime').value=due.time;updateLoanPreview()}
function openNewLoan(){if(!canOriginate())return;if(!db.groups.length)return $('#groupDialog').showModal();if(!db.borrowers.length)return $('#borrowerDialog').showModal();const s=db.settings;$('#loanForm').reset();$('#editLoanId').value='';$('#loanDialogTitle').textContent='Add New Loan';$('#saveLoanBtn').textContent='Save Loan';$('#loanBorrower').disabled=false;$('#principal').disabled=false;$('#interestRate').value=s.defaultInterestRate;$('#feeType').value=s.defaultFeeType;$('#feeValue').value=s.defaultFeeValue;$('#durationValue').value=s.defaultDurationValue;$('#durationUnit').value=s.defaultDurationUnit;$('#dateGiven').value=today;$('#timeGiven').value=currentTime;updateDueFromDuration();updateLoanPreview();$('#loanDialog').showModal()}
window.editLoan=loanId=>{const l=db.loans.find(x=>x.id===loanId);if(!l||!canOriginate()||!canAccessLoan(l))return;$('#editLoanId').value=l.id;$('#loanDialogTitle').textContent='Adjust Loan Terms';$('#saveLoanBtn').textContent='Save Adjustments';$('#loanBorrower').value=l.borrowerId;$('#loanBorrower').disabled=true;$('#principal').value=l.principal;$('#principal').disabled=totalPaid(l)>0;$('#interestRate').value=l.interestRate;$('#feeType').value=l.feeType;$('#feeValue').value=l.feeValue;$('#durationValue').value=l.durationValue;$('#durationUnit').value=l.durationUnit;$('#dateGiven').value=l.dateGiven;$('#timeGiven').value=l.timeGiven;$('#dueDate').value=l.dueDate;$('#dueTime').value=l.dueTime;$('#loanNotes').value=l.notes||'';updateLoanPreview();$('#loanDialog').showModal()};
$('#newLoanBtn').onclick=openNewLoan;
['principal','interestRate','feeType','feeValue','durationValue','durationUnit'].forEach(id=>$('#'+id).addEventListener('input',updateLoanPreview));['dateGiven','timeGiven','durationValue','durationUnit'].forEach(id=>$('#'+id).addEventListener('change',updateDueFromDuration));

$('#loanForm').onsubmit=e=>{e.preventDefault();if(!canOriginate())return alert('Only an administrator or lender can create or adjust loans.');const editId=$('#editLoanId').value,principal=Number($('#principal').value),rate=Number($('#interestRate').value),feeType=$('#feeType').value,feeValue=Number($('#feeValue').value),terms=calcTerms(principal,rate,feeType,feeValue);if(dateTimeValue($('#dueDate').value,$('#dueTime').value)<=dateTimeValue($('#dateGiven').value,$('#timeGiven').value))return alert('Due date and time must be after the loan is given.');if(editId){const l=db.loans.find(x=>x.id===editId);if(terms.total+0.005<totalPaid(l))return alert('Adjusted total cannot be lower than payments already received.');const old=`Interest ${pct(l.interestRate)}, fee ${money(l.feeAmount)}, due ${l.dueDate} ${l.dueTime}`;Object.assign(l,{principal,interestRate:rate,interestAmount:terms.interest,feeType,feeValue,feeAmount:terms.fee,durationValue:Number($('#durationValue').value),durationUnit:$('#durationUnit').value,dateGiven:$('#dateGiven').value,timeGiven:$('#timeGiven').value,dueDate:$('#dueDate').value,dueTime:$('#dueTime').value,notes:$('#loanNotes').value.trim()});l.adjustments.push({id:uid(),date:today,time:currentTime,userId:currentUser.id,note:`Changed from ${old} to interest ${pct(rate)}, fee ${money(terms.fee)}, due ${l.dueDate} ${l.dueTime}`})}else{db.loans.push({id:uid(),borrowerId:$('#loanBorrower').value,principal,interestRate:rate,interestAmount:terms.interest,feeType,feeValue,feeAmount:terms.fee,durationValue:Number($('#durationValue').value),durationUnit:$('#durationUnit').value,dateGiven:$('#dateGiven').value,timeGiven:$('#timeGiven').value,dueDate:$('#dueDate').value,dueTime:$('#dueTime').value,notes:$('#loanNotes').value.trim(),createdBy:currentUser.id,createdAt:`${$('#dateGiven').value}T${$('#timeGiven').value}`,payments:[],adjustments:[]})}$('#loanBorrower').disabled=false;$('#principal').disabled=false;e.target.reset();$('#loanDialog').close();save()};

window.openPayment=loanId=>{const l=db.loans.find(x=>x.id===loanId);if(!l||!canCollect()||!canAccessLoan(l))return alert('You do not have access to this loan.');const b=getBorrower(l.borrowerId),a=allocation(l);$('#paymentLoanId').value=loanId;$('#paymentAmount').value=balance(l).toFixed(2);$('#paymentDate').value=today;$('#paymentTime').value=currentTime;$('#paymentNotes').value='';$('#paymentLoanSummary').innerHTML=`<strong>${esc(b?.name||'Borrower')}</strong><div class="muted">Balance ${money(balance(l))} • Fee ${money(a.feeOutstanding)} • Interest ${money(a.interestOutstanding)} • Principal ${money(a.principalOutstanding)}</div>`;$('#paymentDialog').showModal()};
$('#paymentForm').onsubmit=e=>{e.preventDefault();if(!canCollect())return alert('You cannot record payments.');const l=db.loans.find(x=>x.id===$('#paymentLoanId').value);if(!l||!canAccessLoan(l))return alert('You do not have access to this loan.');const amt=Number($('#paymentAmount').value);if(amt>balance(l)+.01)return alert('Payment cannot exceed the remaining balance.');l.payments.push({id:uid(),amount:amt,date:$('#paymentDate').value,time:$('#paymentTime').value,notes:$('#paymentNotes').value.trim(),recordedBy:currentUser.id});e.target.reset();$('#paymentDialog').close();save()};
$('#borrowerForm').onsubmit=e=>{e.preventDefault();if(!canManagePeople())return alert('Only an administrator or lender can add borrowers.');if(!$('#borrowerGroup').value)return alert('Add a group first.');db.borrowers.push({id:uid(),name:$('#borrowerName').value.trim(),phone:$('#borrowerPhone').value.trim(),groupId:$('#borrowerGroup').value});e.target.reset();$('#borrowerDialog').close();save()};
$('#groupForm').onsubmit=e=>{e.preventDefault();if(!canManagePeople())return alert('Only an administrator or lender can add groups.');db.groups.push({id:uid(),name:$('#groupName').value.trim(),contact:$('#groupContact').value.trim()});e.target.reset();$('#groupDialog').close();save()};
$('#userForm').onsubmit=e=>{e.preventDefault();if(!isAdmin())return;const username=$('#userUsername').value.trim().toLowerCase();if(db.users.some(u=>u.username.toLowerCase()===username))return alert('That username already exists.');const role=$('#userRole').value,assignedGroupIds=role==='manager'?[...$('#userGroupScope').querySelectorAll('input:checked')].map(x=>x.value):[];db.users.push({id:uid(),name:$('#userName').value.trim(),username,password:$('#userPassword').value,role,active:true,assignedGroupIds});e.target.reset();$('#userDialog').close();save()};
function updateUserScopeVisibility(){const wrap=$('#userGroupScopeWrap');if(wrap)wrap.classList.toggle('hidden',$('#userRole').value!=='manager')}
$('#userRole').addEventListener('change',updateUserScopeVisibility);
window.toggleManagerGroup=(userId,groupId,checked)=>{if(!isAdmin())return;const u=getUser(userId);u.assignedGroupIds=u.assignedGroupIds||[];u.assignedGroupIds=checked?[...new Set([...u.assignedGroupIds,groupId])]:u.assignedGroupIds.filter(id=>id!==groupId);save()};
$('#settingsForm').onsubmit=e=>{e.preventDefault();if(!(isAdmin()||isLender()))return;Object.assign(db.settings,{defaultInterestRate:Number($('#defaultInterest').value),defaultFeeType:$('#defaultFeeType').value,defaultFeeValue:Number($('#defaultFeeValue').value),defaultDurationValue:Number($('#defaultDurationValue').value),defaultDurationUnit:$('#defaultDurationUnit').value,openingCapital:Number($('#openingCapital').value),currency:$('#currencySelect').value});save();alert('Settings saved.')};
window.toggleUser=id=>{if(!isAdmin())return;const u=getUser(id);u.active=u.active===false;save()};
window.deleteLoan=id=>{if(!isAdmin())return;if(confirm('Delete this loan and all of its payment history?')){db.loans=db.loans.filter(l=>l.id!==id);save()}};

function downloadFile(name,content,type){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('#exportLedgerBtn').onclick=()=>{const rows=buildLedger(),csv=[['Date','Time','Type','Borrower','Group','Details','Money Out','Money In','Cash After','Recorded By'],...rows.map(e=>[e.date,e.time,e.type,e.borrower,e.group,e.details,e.out,e.in,e.cashAfter,e.user])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');downloadFile(`golden-day-ledger-${today}.csv`,csv,'text/csv')};
$('#exportBtn').onclick=()=>downloadFile(`golden-day-club-backup-${today}.json`,JSON.stringify(db,null,2),'application/json');
$('#importInput').onchange=async e=>{try{const incoming=JSON.parse(await e.target.files[0].text());if(!incoming.groups||!incoming.borrowers||!incoming.loans||!incoming.users)throw Error();db=incoming;normalizeDB();save();alert('Backup restored.')}catch{alert('That backup file is not valid.')}e.target.value=''};
$('#resetSeedBtn').onclick=()=>{if(confirm('Replace all current records with the original sample portfolio?')){db=seedDB();localStore.setItem(STORE_KEY,JSON.stringify(db));currentUser=db.users[0];sessionStore.setItem(SESSION_KEY,currentUser.id);render()}};
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(b=>b.classList.remove('active'));$$('.panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab).classList.add('active');updateFabVisibility();window.scrollTo({top:0,behavior:'smooth'})});
$$('[data-close]').forEach(b=>b.onclick=()=>{const dialog=$('#'+b.dataset.close);if(b.dataset.close==='loanDialog'){$('#loanBorrower').disabled=false;$('#principal').disabled=false}dialog.close()});
['loanSearch','ledgerSearch'].forEach(id=>$('#'+id).addEventListener('input',()=>id==='loanSearch'?renderLoans():renderLedger()));
['loanStatusFilter','loanGroupFilter'].forEach(id=>$('#'+id).addEventListener('change',renderLoans));
['ledgerTypeFilter','ledgerOrder'].forEach(id=>$('#'+id).addEventListener('change',renderLedger));
['dashRange','dashGroup','dashStatus'].forEach(id=>$('#'+id).addEventListener('change',renderDashboard));$('#refreshDashboard').onclick=renderDashboard;
let deferredInstallPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installAppBtn').classList.remove('hidden')});$('#installAppBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installAppBtn').classList.add('hidden')};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
const sessionUser=db.users.find(u=>u.id===sessionStore.getItem(SESSION_KEY)&&u.active!==false);if(sessionUser)showApp(sessionUser);
